### ISSUE TITLE
for swift?

### ISSUE THREAD

**Issue by davut5** [julapy/ofxiOSVideoWriter#1]
how can i use it for swift?

**Comment by julapy** [comment]
hmm not sure... i haven't done too much swift.
can't you mash up swift and obj-c?

**Comment by davut5** [comment]
oh ok sir. i am playing youtube video in a webview. and i want to record this video with your library. Can i make it?

**Comment by julapy** [comment]
no... its only for recording opengl textures.
so more for recording games and other things that are made with opengl.
