### ISSUE TITLE
iOS : How to record from Microphone

### ISSUE THREAD

**Issue by aisgirish** [julapy/ofxiOSVideoWriter#2]
Hi,

I am developing the app which required to video recording. I looked into iosScreenRecordExample but it record from video player.
But I need to record audio from microphone.

Please help me.

**Comment by julapy** [comment]
that is quite difficult,
i had trouble getting this feature to work also.
so unfortunately i can't help you there...
if you do get this feature working, please submit a PR to this repo.

**Comment by aisgirish** [comment]
It make me sad.
I will try to find solution for this.
Thanks.
