### ISSUE TITLE
[warning] ofGLProgrammableRenderer: draw(): texture is not allocated

### ISSUE THREAD

**Issue by thinium** [julapy/ofxiOSVideoWriter#4]
Hi,
I'm trying to use this addon with the latest version of ios openframeworks (for iPad). When I toggle the record button, it shows "Recording" on the top left corner, but the video is stuck in the first frame, and the music stops, and the current frame number stays at 000000. In the console, it shows a warning:
 [warning] ofGLProgrammableRenderer: draw(): texture is not allocated

When I toggle the recording button again, the music and video starts to run again. Is this expected behavior? Where can I find the recorded video?

Thanks in advance!

**Comment by julapy** [comment]
hey @ukelady, which OF version are you running it with?
last time i checked this addon was working with the OF094

**Comment by julapy** [comment]
just tested it again on my iphone and it seems to be working fine.
video file is saved into your phones documents folder,
you can access it with the itunes app.

**Comment by thinium** [comment]
Hi Lukasz! I am using Openframeworks of_v0.9.3_ios_release. I'll update to
the latest version then.

I'll close this issue for now and report again when the same issue emerge.
Thanks!
